name: Two Jobs Push Workflow

# Trigger automatically whenever you push code to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print from Job One
        run: echo "I am from the first job"

  job-two:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print from Job Two
        run: echo "I am from the second job"